#pragma once
// SessionId allocator — monotonic counter with a 60-second reuse-blacklist.
// PROTOCOL_SPEC.md section 9:
//   - Generated by RemoteTool
//   - uint32, 0 is reserved for connection-level messages
//   - No reuse within the same Tunnel lifetime
//   - Increment from 1; before wrap-around the Tunnel must be rebuilt
//   - Keep a short-lived (60 s) record of recently closed IDs to gracefully
//     ignore a late CLOSE for an already-released session.
#include <cstdint>
#include <chrono>
#include <deque>

namespace rmt::session {

class SessionIdAllocator {
public:
    SessionIdAllocator() = default;

    // Returns the next unused SessionId (>= 1), or 0 when the 32-bit space
    // is exhausted (callers must tear down the Tunnel).
    std::uint32_t allocate() {
        while (next_id_ < 0xFFFFFFFFu) {
            std::uint32_t candidate = next_id_++;
            if (candidate == 0) continue;  // 0 is reserved
            purge_expired();
            if (is_blacklisted(candidate)) continue;
            return candidate;
        }
        return 0;  // exhausted
    }

    // Register a released id so late-arriving CLOSE frames for recently-deleted
    // sessions can be silently ignored instead of reported as protocol errors.
    void release(std::uint32_t id) {
        if (id == 0) return;
        purge_expired();
        blacklist_.push_back({id, clock::now()});
    }

    // Returns true if id is in the 60-second reuse-blacklist.
    bool is_blacklisted(std::uint32_t id) const {
        for (const auto& e : blacklist_) {
            if (e.id == id) return true;
        }
        return false;
    }

private:
    using clock = std::chrono::steady_clock;
    struct Entry { std::uint32_t id; clock::time_point released; };

    void purge_expired() {
        auto now = clock::now();
        while (!blacklist_.empty() &&
               now - blacklist_.front().released > std::chrono::seconds(60)) {
            blacklist_.pop_front();
        }
    }

    std::uint32_t next_id_ = 1;
    mutable std::deque<Entry> blacklist_;
};

}  // namespace rmt::session
