# CMake generated Testfile for 
# Source directory: D:/coding/RemoteTool
# Build directory: D:/coding/RemoteTool/build-rel
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[frame_test]=] "D:/coding/RemoteTool/build-rel/bin/frame_test.exe")
set_tests_properties([=[frame_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/coding/RemoteTool/CMakeLists.txt;91;add_test;D:/coding/RemoteTool/CMakeLists.txt;0;")
add_test([=[scope_guard_test]=] "D:/coding/RemoteTool/build-rel/bin/scope_guard_test.exe")
set_tests_properties([=[scope_guard_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/coding/RemoteTool/CMakeLists.txt;96;add_test;D:/coding/RemoteTool/CMakeLists.txt;0;")
add_test([=[log_test]=] "D:/coding/RemoteTool/build-rel/bin/log_test.exe")
set_tests_properties([=[log_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/coding/RemoteTool/CMakeLists.txt;101;add_test;D:/coding/RemoteTool/CMakeLists.txt;0;")
add_test([=[strict_json_test]=] "D:/coding/RemoteTool/build-rel/bin/strict_json_test.exe")
set_tests_properties([=[strict_json_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/coding/RemoteTool/CMakeLists.txt;106;add_test;D:/coding/RemoteTool/CMakeLists.txt;0;")
add_test([=[atomic_write_test]=] "D:/coding/RemoteTool/build-rel/bin/atomic_write_test.exe")
set_tests_properties([=[atomic_write_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/coding/RemoteTool/CMakeLists.txt;111;add_test;D:/coding/RemoteTool/CMakeLists.txt;0;")
add_test([=[target_whitelist_test]=] "D:/coding/RemoteTool/build-rel/bin/target_whitelist_test.exe")
set_tests_properties([=[target_whitelist_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/coding/RemoteTool/CMakeLists.txt;116;add_test;D:/coding/RemoteTool/CMakeLists.txt;0;")
add_test([=[secret_store_test]=] "D:/coding/RemoteTool/build-rel/bin/secret_store_test.exe")
set_tests_properties([=[secret_store_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/coding/RemoteTool/CMakeLists.txt;121;add_test;D:/coding/RemoteTool/CMakeLists.txt;0;")
add_test([=[config_schema_test]=] "D:/coding/RemoteTool/build-rel/bin/config_schema_test.exe")
set_tests_properties([=[config_schema_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/coding/RemoteTool/CMakeLists.txt;126;add_test;D:/coding/RemoteTool/CMakeLists.txt;0;")
add_test([=[connection_test]=] "D:/coding/RemoteTool/build-rel/bin/connection_test.exe")
set_tests_properties([=[connection_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/coding/RemoteTool/CMakeLists.txt;131;add_test;D:/coding/RemoteTool/CMakeLists.txt;0;")
add_test([=[messages_test]=] "D:/coding/RemoteTool/build-rel/bin/messages_test.exe")
set_tests_properties([=[messages_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/coding/RemoteTool/CMakeLists.txt;136;add_test;D:/coding/RemoteTool/CMakeLists.txt;0;")
add_test([=[agent_connection_test]=] "D:/coding/RemoteTool/build-rel/bin/agent_connection_test.exe")
set_tests_properties([=[agent_connection_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/coding/RemoteTool/CMakeLists.txt;141;add_test;D:/coding/RemoteTool/CMakeLists.txt;0;")
add_test([=[device_manager_test]=] "D:/coding/RemoteTool/build-rel/bin/device_manager_test.exe")
set_tests_properties([=[device_manager_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/coding/RemoteTool/CMakeLists.txt;146;add_test;D:/coding/RemoteTool/CMakeLists.txt;0;")
add_test([=[hello_heartbeat_test]=] "D:/coding/RemoteTool/build-rel/bin/hello_heartbeat_test.exe")
set_tests_properties([=[hello_heartbeat_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/coding/RemoteTool/CMakeLists.txt;151;add_test;D:/coding/RemoteTool/CMakeLists.txt;0;")
add_test([=[multi_session_test]=] "D:/coding/RemoteTool/build-rel/bin/multi_session_test.exe")
set_tests_properties([=[multi_session_test]=] PROPERTIES  DISABLED "TRUE" TIMEOUT "30" _BACKTRACE_TRIPLES "D:/coding/RemoteTool/CMakeLists.txt;156;add_test;D:/coding/RemoteTool/CMakeLists.txt;0;")
add_test([=[agent_session_test]=] "D:/coding/RemoteTool/build-rel/bin/agent_session_test.exe")
set_tests_properties([=[agent_session_test]=] PROPERTIES  TIMEOUT "15" _BACKTRACE_TRIPLES "D:/coding/RemoteTool/CMakeLists.txt;162;add_test;D:/coding/RemoteTool/CMakeLists.txt;0;")
add_test([=[session_manager_test]=] "D:/coding/RemoteTool/build-rel/bin/session_manager_test.exe")
set_tests_properties([=[session_manager_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/coding/RemoteTool/CMakeLists.txt;168;add_test;D:/coding/RemoteTool/CMakeLists.txt;0;")
add_test([=[config_loader_test]=] "D:/coding/RemoteTool/build-rel/bin/config_loader_test.exe")
set_tests_properties([=[config_loader_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/coding/RemoteTool/CMakeLists.txt;173;add_test;D:/coding/RemoteTool/CMakeLists.txt;0;")
subdirs("third_party/mbedtls")
